CREATE TABLE login_attempts (
  ip        TEXT PRIMARY KEY,
  failed    INTEGER NOT NULL DEFAULT 0,
  first_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
